version:  "3.9"

services:
  
  # create a service with rabbitMQ 
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name:  message-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    restart: always
    networks:
      - dev-net

  sender: 
    container_name: sender
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./build/sender/Dockerfile-sender
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - dev-net
    depends_on:
      - message-broker

  consumer: 
    container_name: consumer
    build:
      context: .
      dockerfile: ./build/consumer/Dockerfile-consumer
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - dev-net
    depends_on:
      - sender 
      - message-broker


networks:
  #creating a docker net
  dev-net:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log: